### ISSUE TITLE
[v2] Error when trying to install edge runtime on Raspbian

### ISSUE THREAD

**Issue by nightparrot** [Azure/iot-edge-v1#453]
Raspberry Pi 3

I am trying to run this command:
`sudo pip install -U azure-iot-edge-runtime-ctl`

And I get this error:

Downloading/unpacking azure-iot-edge-runtime-ctl
  Could not find a version that satisfies the requirement azure-iot-edge-runtime                                                                                                                                                             -ctl (from versions: 1.0.0rc17, 1.0.0rc14, 1.0.0rc11, 1.0.0rc17, 1.0.0rc14, 1.0.                                                                                                                                                             0rc13, 1.0.0rc11, 1.0.0rc13)
Cleaning up...
No distributions matching the version for azure-iot-edge-runtime-ctl
Storing debug log for failure in /root/.pip/pip.log

Here is the pip.log content:

------------------------------------------------------------
/usr/bin/pip run on Wed Jan  3 14:29:29 2018
Downloading/unpacking azure-iot-edge-runtime-ctl
  Getting page https://pypi.python.org/simple/azure-iot-edge-runtime-ctl/
  URLs to search for versions for azure-iot-edge-runtime-ctl:
  * https://pypi.python.org/simple/azure-iot-edge-runtime-ctl/
  Analyzing links from page https://pypi.python.org/simple/azure-iot-edge-runtime-ctl/
    Found link https://pypi.python.org/packages/0b/ee/95081c9d188c9277873608fb0093d8c836842feaabbf7d008f3ac4035c85/azure_iot_edge_runtime_ctl-1.0.0rc17-py2.py3-none-any.whl#md5=16abe73817c87b69cd70ad8fe994937e (from https://pypi.python.$
    Found link https://pypi.python.org/packages/22/51/41c972427bb410521fc72772c59a140fe841f7c51edb45aefc44e2d202ad/azure_iot_edge_runtime_ctl-1.0.0rc14-py2.py3-none-any.whl#md5=6bab1f1c8e9df7130bd500bf1bbc9105 (from https://pypi.python.$
    Found link https://pypi.python.org/packages/57/61/1716c5d31f5db0e66e02847ea288ee7b22053ae8dcbcb2b6720ddc41e4e4/azure_iot_edge_runtime_ctl-1.0.0rc11-py2.py3-none-any.whl#md5=47cb95a833dfbf6452ec2d22b0ca7ea6 (from https://pypi.python.$
    Found link https://pypi.python.org/packages/76/ff/dcb1c1d55dc69a809e6f4b1aa3a83eba578e696b4461af26cacc4b00a9f8/azure-iot-edge-runtime-ctl-1.0.0rc17.tar.gz#md5=519370e8c1a87f9ff96c94a7201f934f (from https://pypi.python.org/simple/azu$
    Found link https://pypi.python.org/packages/85/12/2de6ec3f9b99f70483531ebbcd81992cc0b0dec07cce64c4342094a31b67/azure-iot-edge-runtime-ctl-1.0.0rc14.tar.gz#md5=6d00e373c03e0c104b234373268314e7 (from https://pypi.python.org/simple/azu$
    Found link https://pypi.python.org/packages/9c/1f/900bb21d98a332083e3ff0ee2b34b3425f22677c32719ed77f9b9803c299/azure_iot_edge_runtime_ctl-1.0.0rc13-py2.py3-none-any.whl#md5=976edcfd0560d05622a4972c381533a4 (from https://pypi.python.$
    Found link https://pypi.python.org/packages/d2/89/423440eb2576d0884e809cd9521a5eb2b6e6c62b429bc6e6e922ff31f715/azure-iot-edge-runtime-ctl-1.0.0rc11.tar.gz#md5=4e1bdac8f9c15fc3fd6e4cbfb09cdec6 (from https://pypi.python.org/simple/azu$
    Found link https://pypi.python.org/packages/d5/24/70683448243956541f32f2c2a77b12c9f9d91c84b69a969842ff7001573b/azure-iot-edge-runtime-ctl-1.0.0rc13.tar.gz#md5=5c8dc93691d89681830bfc7af3264b46 (from https://pypi.python.org/simple/azu$
  Ignoring link https://pypi.python.org/packages/0b/ee/95081c9d188c9277873608fb0093d8c836842feaabbf7d008f3ac4035c85/azure_iot_edge_runtime_ctl-1.0.0rc17-py2.py3-none-any.whl#md5=16abe73817c87b69cd70ad8fe994937e (from https://pypi.python$
  Ignoring link https://pypi.python.org/packages/22/51/41c972427bb410521fc72772c59a140fe841f7c51edb45aefc44e2d202ad/azure_iot_edge_runtime_ctl-1.0.0rc14-py2.py3-none-any.whl#md5=6bab1f1c8e9df7130bd500bf1bbc9105 (from https://pypi.python$
  Ignoring link https://pypi.python.org/packages/57/61/1716c5d31f5db0e66e02847ea288ee7b22053ae8dcbcb2b6720ddc41e4e4/azure_iot_edge_runtime_ctl-1.0.0rc11-py2.py3-none-any.whl#md5=47cb95a833dfbf6452ec2d22b0ca7ea6 (from https://pypi.python$
  Ignoring link https://pypi.python.org/packages/76/ff/dcb1c1d55dc69a809e6f4b1aa3a83eba578e696b4461af26cacc4b00a9f8/azure-iot-edge-runtime-ctl-1.0.0rc17.tar.gz#md5=519370e8c1a87f9ff96c94a7201f934f (from https://pypi.python.org/simple/az$
  Ignoring link https://pypi.python.org/packages/85/12/2de6ec3f9b99f70483531ebbcd81992cc0b0dec07cce64c4342094a31b67/azure-iot-edge-runtime-ctl-1.0.0rc14.tar.gz#md5=6d00e373c03e0c104b234373268314e7 (from https://pypi.python.org/simple/az$
  Ignoring link https://pypi.python.org/packages/9c/1f/900bb21d98a332083e3ff0ee2b34b3425f22677c32719ed77f9b9803c299/azure_iot_edge_runtime_ctl-1.0.0rc13-py2.py3-none-any.whl#md5=976edcfd0560d05622a4972c381533a4 (from https://pypi.python$
  Ignoring link https://pypi.python.org/packages/d2/89/423440eb2576d0884e809cd9521a5eb2b6e6c62b429bc6e6e922ff31f715/azure-iot-edge-runtime-ctl-1.0.0rc11.tar.gz#md5=4e1bdac8f9c15fc3fd6e4cbfb09cdec6 (from https://pypi.python.org/simple/az$
  Ignoring link https://pypi.python.org/packages/d5/24/70683448243956541f32f2c2a77b12c9f9d91c84b69a969842ff7001573b/azure-iot-edge-runtime-ctl-1.0.0rc13.tar.gz#md5=5c8dc93691d89681830bfc7af3264b46 (from https://pypi.python.org/simple/az$
  Could not find a version that satisfies the requirement azure-iot-edge-runtime-ctl (from versions: 1.0.0rc17, 1.0.0rc14, 1.0.0rc11, 1.0.0rc17, 1.0.0rc14, 1.0.0rc13, 1.0.0rc11, 1.0.0rc13)
Cleaning up...
No distributions matching the version for azure-iot-edge-runtime-ctl
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for azure-iot-edge-runtime-ctl

Details of the Linux:

Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

Running Python 2.7.9  and Python 3.4.2

Docker Server Version: 17.12.0-ce

**Comment by nightparrot** [comment]
I have found a solution provided by @jonbgallant blog [https://blog.jongallant.com/2017/11/azure-iot-edge-raspberrypi/](url)
I agree that this should be noted or documented on the official guide.


3. Upgrade Setup Tools
You will find the Azure IoT Edge Runtime on pypi here, which has the Raspbian specific steps, which I’ve included here as well. I’ve asked the team to include these steps in the Linux setup tutorial guide. This issue is being tracked on GitHub here.

Open a Terminal and run the following:


sudo pip install --upgrade setuptools pip
sudo apt install python2.7-dev libffi-dev libssl-dev -y

**Comment by aribeironovaes** [comment]
Closing this issue due to inactivity and by believing this is working. 
If it's not the case, please, find or open an issue on v2 specific github: https://github.com/Azure/iotedge
