### ISSUE TITLE
[V2] Error adding desired property and direct method subscriptions, works with a iotedgectl restart

### ISSUE THREAD

**Issue by chriswaters78** [Azure/iot-edge-v1#586]
Looks like this may be related to #572.

I am developing some modules on Edge V2 and testing these on a raspberry pi (Arm32v7) with runtime 1.0.0rc22.

I have an issue with setting direct method and desired property callbacks.

```
            var ioTHubModuleClient = DeviceClient.CreateFromConnectionString(connectionString, settings);
            await ioTHubModuleClient.SetMethodHandlerAsync("setpayload", SetPayloadMethodCallback, null);
            await ioTHubModuleClient.SetDesiredPropertyUpdateCallbackAsync(OnDesiredPropertiesUpdate, null);
```

When I deploy this module and restart the edge runtime on the pi, these work as expected.

However, if I deploy but don't restart the edge runtime, module twin updates don't trigger the callback and I get a 500 response calling the direct method. The rest of the module works fine (it sends out regular messages like the sample temperature probe module).

In the edgeHub logs the last two lines below seem to indicate a failure to subscribe to the desired property and direct method events:

```
2018-04-26 15:14:05.017 +00:00 [INF] - Obtained edge hub config patch update from module twin
2018-04-26 15:14:05.210 +00:00 [INF] - Updating edge hub configuration
2018-04-26 15:14:05.473 +00:00 [INF] - Set the following 1 route(s) in edge hub
2018-04-26 15:14:05.474 +00:00 [INF] - route: FROM /* INTO $upstream
2018-04-26 15:14:05.474 +00:00 [INF] - Updated message store TTL to 7200 seconds
2018-04-26 15:14:05.474 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-04-26 15:14:07.743 +00:00 [WRN] - Closing connection for device: devpi1/mockmodbus, Microsoft.Azure.Devices.ProtocolGateway.ProtocolGatewayException: Channel closed.,
2018-04-26 15:14:07.766 +00:00 [INF] - Disposing MessagingServiceClient for device Id devpi1/mockmodbus because of exception - Microsoft.Azure.Devices.ProtocolGateway.ProtocolGatewayException: Channel closed.
2018-04-26 15:14:07.781 +00:00 [INF] - Setting device proxy inactive for device Id devpi1/mockmodbus
2018-04-26 15:14:07.828 +00:00 [INF] - Closing receiver for device devpi1/mockmodbus
2018-04-26 15:14:07.956 +00:00 [INF] - Closed cloud proxy for device devpi1/mockmodbus
2018-04-26 15:14:07.958 +00:00 [INF] - Device connection removed for device devpi1/mockmodbus
2018-04-26 15:14:07.974 +00:00 [INF] - Remove device connection for device devpi1/mockmodbus
2018-04-26 15:14:24.006 +00:00 [INF] - Attempting to connect to IoT Hub for client devpi1/mockmodbus via AMQP...
2018-04-26 15:14:24.008 +00:00 [INF] - New token requested by client devpi1/mockmodbus, but using existing token as it is usable.
2018-04-26 15:14:24.114 +00:00 [INF] - Connected to IoT Hub for client devpi1/mockmodbus via AMQP, with client operation timeout 60000.
2018-04-26 15:14:24.114 +00:00 [INF] - Closing receiver for device devpi1/mockmodbus
2018-04-26 15:14:24.115 +00:00 [INF] - Closed cloud proxy for device devpi1/mockmodbus
2018-04-26 15:14:24.121 +00:00 [WRN] - Error adding subscription $iothub/twin/PATCH/properties/desired/# for client devpi1/mockmodbus.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SetupDesiredPropertyUpdatesAsync() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 136
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.SessionStatePersistenceProvider.<>c__DisplayClass10_0.<<ProcessSessionSubscriptions>b__0>d.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/SessionStatePersistenceProvider.cs:line 77
2018-04-26 15:14:24.312 +00:00 [WRN] - Error adding subscription $iothub/methods/POST/# for client devpi1/mockmodbus.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SetupCallMethodAsync() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 132
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.SessionStatePersistenceProvider.<>c__DisplayClass10_0.<<ProcessSessionSubscriptions>b__0>d.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/SessionStatePersistenceProvider.cs:line 66
```

**Comment by varunpuranik** [comment]
What version of the EdgeHub are you using? You can find the version at the top of the EdgeHub logs (if you cannot find it, you can send us the entire logs). 
From the logs, this looks similar to a bug that was fixed in version 1.0.0-preview022. If you are using a previous version, can you try version 1.0.0-preview022? If it is indeed this version, then let us know - we will mark it as a bug and investigate.

**Comment by chriswaters78** [comment]
Thanks for the prompt response. I double checked my edge runtime version, this is 1.0.0rc22. I noticed the edgeHub and edgeAgent modules were still 1.0.0-preview, so I updated both of these to 1.0.0-preview022 but I get the same issue.

Do you have any idea of when rc23 will be available? This is a critical bug for our project, as it is not feasible to SSH on to the pi's and restart iotedgectl for each deployment. Any workarounds in the mean time? It doesn't seem possible to trigger a restart via the hub itself.

**Comment by varunpuranik** [comment]
RC23 is planned for release sometime in May. But unfortunately the fix for the subscriptions might be available only by GA.

**Comment by damonbarry** [comment]
Fixed. Closing...
