### ISSUE TITLE
Routing issue to edge Function

### ISSUE THREAD

**Issue by davebanthorpe** [Azure/iot-edge-v1#617]
HI,

I have 2 modules running on an edge device. One of which is a modbus server (the MSFT one from here https://github.com/Azure/iot-edge-modbus) and the other is a function module. The function is designed to read data from the modbus module, and if necessary send data back to modbus.

I am having apparent issues with routing where by data from the modbus module is getting sent fine to IoT Hub in the cloud, but the function is not receiving trigger data based on a new message from modbus module.

This is my routing:

```
{
  "routes": {
    "modbusToFunction": "FROM /messages/modules/modbus/outputs/modbusOutput INTO BrokeredEndpoint(\"/modules/pifunc/inputs/input1\")",
    "modbusToCloud": "FROM /messages/modules/modbus/outputs/modbusOutput INTO $upstream",
    "functionToModbus": "FROM /messages/modules/pifunc/outputs/* INTO BrokeredEndpoint(\"/modules/modbus/inputs/input1\")"
  }
}

```

This is the function app trigger:

`public static async Task Run(Message messageReceived, IAsyncCollector<Message> output, TraceWriter log)
`

Sometimes it works, sometimes it doesn't. What is interesting is that the function is first in the routing list so if there was something fundamentally wrong then the second route "modbusToCloud" would not be working, but it is.

Any suggestions?

**Comment by davebanthorpe** [comment]
FYI the only way I have found to "cure" this is to completely deploy the edge device and modules again via:

- iotedgectl stop
- docker rm <modules>
- delete and create edge device in Azure again
- iotedgectl setup  .....
- iotedgectl start
- deploy modules 

Interestingly, when I do that and look at the logs of the function app, it is streaming LOADS of old messages and processing them. This would lead me to assume 2 things:

1) the "bug" noted above is queue/hub related
2) deleting and re-creating does NOT clear the old queue

**Comment by varunpuranik** [comment]
HI davebanthorpe,

It seems like what is going on is that the functions module is sometimes losing connection to the EdgeHub (or not responding to it) for some reason. In that case, the edgeHub is unable to send messages to the functions module. When you restart the system, the functions module re-connects with the EdgeHub, and then the EdgeHub is able to send messages to it again. 

As for the routes - they are not in order or with priority (each route is processed independently of each other, so whether a route is first or second doesn't matter). 

And for clearing the old queue - EdgeHub stores messages (the queue) inside the container, unless you mount a volume into EdgeHub and set the right Environment variables to make it use the mounted volume for storage. So, if you are not doing the volume mount, then you can clear the queue by removing the edgeHub container - $>sudo docker rm -f edgeHub

I am not sure why the functions module is losing connection (or becoming inactive), but if you send over logs from the edgeHub and functions modules, I can take a look.

Thanks,
-Varun

**Comment by davebanthorpe** [comment]
HI Varun - after doing more testing it seems the issue is not specific to this function app as I have another system where Edge is playing up. Everything was running fine until I rebooted the machine. The modules start up - and I can see from the logs that data is coming into the downstream module. But no data is leaving the edgeHub - nothing is seen in device explorer. Question is - where does the problem lie - the downstream module (modbus) or edgeHub?

Here is the startup of the edgeHub. The only error I can see is this but this is immediately followed by success statements so I don't know if it corrected itself or not?

```
2018-06-06 09:01:08.767 +00:00 [WRN] - Error adding subscription $iothub/twin/PATCH/properties/desired/# for client dev/modbus.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SetupDesiredPropertyUpdatesAsync() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 136
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.SessionStatePersistenceProvider.<>c__DisplayClass10_0.<<ProcessSessionSubscriptions>b__0>d.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/SessionStatePersistenceProvider.cs:line 77
```


```
2018-06-06 08:58:24.298 +00:00 [INF] - Initializing configuration
2018-06-06 08:58:24.665 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2018-06-06 08:58:24.704 +00:00 [INF] - Attempting to connect to IoT Hub for client dev/$edgeHub via AMQP...
2018-06-06 08:58:26.724 +00:00 [INF] - Connected to IoT Hub for client dev/$edgeHub via AMQP, with client operation timeout 60000.
2018-06-06 08:58:26.735 +00:00 [INF] - Created cloud connection for client dev/$edgeHub
2018-06-06 08:58:26.736 +00:00 [INF] - New cloud connection created for device dev/$edgeHub
2018-06-06 08:58:26.751 +00:00 [INF] - New device connection for device dev/$edgeHub
2018-06-06 08:58:27.534 +00:00 [INF] - Created new message store
2018-06-06 08:58:27.535 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-06-06 08:58:29.592 +00:00 [INF] - Obtained edge hub config from module twin
2018-06-06 08:58:29.690 +00:00 [INF] - Set the following 3 route(s) in edge hub
2018-06-06 08:58:29.691 +00:00 [INF] - modbusToFunction: FROM /messages/modules/modbus/outputs/modbusOutput INTO BrokeredEndpoint("/modules/pifunc/inputs/input1")
2018-06-06 08:58:29.691 +00:00 [INF] - modbusToCloud: FROM /messages/modules/modbus/outputs/modbusOutput INTO $upstream
2018-06-06 08:58:29.691 +00:00 [INF] - functionToModbus: FROM /messages/modules/pifunc/outputs/output1 INTO BrokeredEndpoint("/modules/modbus/inputs/input1")
2018-06-06 08:58:29.692 +00:00 [INF] - Updated message store TTL to 7200 seconds
2018-06-06 08:58:29.693 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-06-06 08:58:29.693 +00:00 [INF] - Initialized edge hub configuration
2018-06-06 08:58:29.740 +00:00 [INF] - Starting protocol heads - (HTTP, MQTT)
2018-06-06 08:58:29.743 +00:00 [INF] - Starting HTTP head
2018-06-06 08:58:29.787 +00:00 [INF] - Starting MQTT head
2018-06-06 08:58:29.844 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2018-06-06 08:58:31.596 +00:00 [INF] - Started MQTT head
2018-06-06 08:58:31.602 +00:00 [INF] - Started HTTP head
2018-06-06 08:58:35.934 +00:00 [INF] - Attempting to connect to IoT Hub for client dev/modbus via AMQP...
2018-06-06 08:58:35.946 +00:00 [INF] - New token requested by client dev/modbus, but using existing token as it is usable.
2018-06-06 08:58:36.280 +00:00 [INF] - Connected to IoT Hub for client dev/modbus via AMQP, with client operation timeout 60000.
2018-06-06 08:58:36.299 +00:00 [INF] - Set subscriptions from session state for dev/modbus on cloud reconnect
2018-06-06 08:58:36.299 +00:00 [INF] - Created cloud connection for client dev/modbus
2018-06-06 08:58:36.299 +00:00 [INF] - New cloud connection created for device dev/modbus
2018-06-06 08:58:36.300 +00:00 [INF] - Successfully authenticated device dev/modbus
2018-06-06 08:58:36.301 +00:00 [INF] - Successfully generated identity for clientId dev/modbus and username davedev/dev/modbus/api-version=2017-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.6.0-preview-001%20%28.NET%20Core%204.6.00001.0%3B%20Linux%204.9.87-linuxkit-aufs%20%231%20SMP%20Wed%20Mar%2014%2015%3A12%3A16%20UTC%202018%3B%20X64%29
2018-06-06 08:58:36.303 +00:00 [INF] - ClientAuthenticated, dev/modbus, 2e789d2b
2018-06-06 08:58:36.329 +00:00 [INF] - New device connection for device dev/modbus
2018-06-06 08:58:36.341 +00:00 [INF] - Bind device proxy for device dev/modbus
2018-06-06 08:58:36.342 +00:00 [INF] - Binding message channel for device Id dev/modbus
2018-06-06 08:58:36.766 +00:00 [INF] - Set subscriptions from session state for dev/modbus
2018-06-06 08:58:36.816 +00:00 [INF] - Attempting to connect to IoT Hub for client dev/pifunc via AMQP...
2018-06-06 08:58:36.817 +00:00 [INF] - New token requested by client dev/pifunc, but using existing token as it is usable.
2018-06-06 08:58:37.130 +00:00 [INF] - Connected to IoT Hub for client dev/pifunc via AMQP, with client operation timeout 60000.
2018-06-06 08:58:37.134 +00:00 [INF] - Set subscriptions from session state for dev/pifunc on cloud reconnect
2018-06-06 08:58:37.134 +00:00 [INF] - Created cloud connection for client dev/pifunc
2018-06-06 08:58:37.134 +00:00 [INF] - New cloud connection created for device dev/pifunc
2018-06-06 08:58:37.135 +00:00 [INF] - Successfully authenticated device dev/pifunc
2018-06-06 08:58:37.135 +00:00 [INF] - Successfully generated identity for clientId dev/pifunc and username davedev/dev/pifunc/api-version=2017-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.6.0-preview-001%20%28.NET%20Core%204.6.0.0%3B%20Linux%204.9.87-linuxkit-aufs%20%231%20SMP%20Wed%20Mar%2014%2015%3A12%3A16%20UTC%202018%3B%20X64%29
2018-06-06 08:58:37.135 +00:00 [INF] - ClientAuthenticated, dev/pifunc, 3cb46c42
2018-06-06 08:58:37.136 +00:00 [INF] - New device connection for device dev/pifunc
2018-06-06 08:58:37.138 +00:00 [INF] - Bind device proxy for device dev/pifunc
2018-06-06 08:58:37.138 +00:00 [INF] - Binding message channel for device Id dev/pifunc
2018-06-06 08:58:37.540 +00:00 [INF] - Set subscriptions from session state for dev/pifunc
2018-06-06 09:01:05.708 +00:00 [WRN] - Closing connection for device: dev/modbus, Microsoft.Azure.Devices.ProtocolGateway.ProtocolGatewayException: Channel closed.,
2018-06-06 09:01:05.709 +00:00 [INF] - Disposing MessagingServiceClient for device Id dev/modbus because of exception - Microsoft.Azure.Devices.ProtocolGateway.ProtocolGatewayException: Channel closed.
2018-06-06 09:01:05.711 +00:00 [INF] - Setting device proxy inactive for device Id dev/modbus
2018-06-06 09:01:05.720 +00:00 [INF] - Closing receiver for device dev/modbus
2018-06-06 09:01:05.777 +00:00 [INF] - Closed cloud proxy for device dev/modbus
2018-06-06 09:01:05.778 +00:00 [INF] - Device connection removed for device dev/modbus
2018-06-06 09:01:05.785 +00:00 [INF] - Remove device connection for device dev/modbus
2018-06-06 09:01:08.440 +00:00 [INF] - Attempting to connect to IoT Hub for client dev/modbus via AMQP...
2018-06-06 09:01:08.440 +00:00 [INF] - New token requested by client dev/modbus, but using existing token as it is usable.
2018-06-06 09:01:08.760 +00:00 [INF] - Connected to IoT Hub for client dev/modbus via AMQP, with client operation timeout 60000.
2018-06-06 09:01:08.760 +00:00 [INF] - Closing receiver for device dev/modbus
2018-06-06 09:01:08.760 +00:00 [INF] - Closed cloud proxy for device dev/modbus
2018-06-06 09:01:08.767 +00:00 [WRN] - Error adding subscription $iothub/twin/PATCH/properties/desired/# for client dev/modbus.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SetupDesiredPropertyUpdatesAsync() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 136
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.SessionStatePersistenceProvider.<>c__DisplayClass10_0.<<ProcessSessionSubscriptions>b__0>d.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/SessionStatePersistenceProvider.cs:line 77
2018-06-06 09:01:08.778 +00:00 [INF] - Set subscriptions from session state for dev/modbus on cloud reconnect
2018-06-06 09:01:08.779 +00:00 [INF] - New cloud connection created for device dev/modbus
2018-06-06 09:01:08.779 +00:00 [INF] - Successfully authenticated device dev/modbus
2018-06-06 09:01:08.779 +00:00 [INF] - Successfully generated identity for clientId dev/modbus and username davedev/dev/modbus/api-version=2017-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.6.0-preview-001%20%28.NET%20Core%204.6.00001.0%3B%20Linux%204.9.87-linuxkit-aufs%20%231%20SMP%20Wed%20Mar%2014%2015%3A12%3A16%20UTC%202018%3B%20X64%29
2018-06-06 09:01:08.779 +00:00 [INF] - ClientAuthenticated, dev/modbus, 4b750f8c
2018-06-06 09:01:08.781 +00:00 [INF] - New device connection for device dev/modbus
2018-06-06 09:01:08.781 +00:00 [INF] - Bind device proxy for device dev/modbus
2018-06-06 09:01:08.781 +00:00 [INF] - Binding message channel for device Id dev/modbus
2018-06-06 09:01:09.077 +00:00 [INF] - Set subscriptions from session state for dev/modbus
2018-06-06 09:01:09.714 +00:00 [INF] - Set subscriptions from session state for dev/modbus
2018-06-06 09:01:09.735 +00:00 [INF] - Set subscriptions from session state for dev/modbus

```

**Comment by varunpuranik** [comment]
We have some fixes in our upcoming release that should fix these issues. You should be able to get that in the coming few weeks (I don't have an exact date yet). 
Meanwhile, looks like you are using preview021 of the edgeHub. Maybe you can try moving to preview022 (it has some bug fixes)

**Comment by davebanthorpe** [comment]
Can you advise how to update to preview022?

**Comment by varunpuranik** [comment]
Create a new deployment with the following edgeHub - microsoft/azureiotedge-hub:1.0.0-preview022

**Comment by davebanthorpe** [comment]
ok will give that a try - thanks

**Comment by davebanthorpe** [comment]
How do I get it to stop deploying the default 1.0-preview edgehub? I specified the new one in the deployment but it still deployed the old version instead.

**Comment by davebanthorpe** [comment]
OK - so some feedback here. I'm seeing that data flow through the hub fails after a few hours and needs the modules restarting to recover. I have seen this with the "standard" preview hub as well. Any suggestions?

**Comment by aribeironovaes** [comment]
HI @davebanthorpe, 

Can you please update your environment and check if you still see this? We have fixed and checked in some bugs on this area. 

Also, I'm closing this issue here since it's not related to v1, it's v2. If you still see this, can you please open an issue on V2 github?

Thanks, 

Angelo Ribeiro.
