### ISSUE TITLE
Error edgeHub connection IoTHub

### ISSUE THREAD

**Issue by carloshm** [Azure/iot-edge-v1#622]
- **V2 issue** 

- **OS version and architecture used:**  Raspbian ARM32

- **Version used:** 1.0_preview 22

- **V2 Docker version and container type** linux

# Description of the issue:
Error from edgeHub and hence all modules with timeout sending to cloud
iothub-explorer with conn string read/write/manager works and says device notconnected
iothub-diagnostics with conn string read/write/manager works

It seems device conn string is not working??
didn't change the environment

# Console log of the issue:
Unhandled Exception: System.AggregateException: One or more errors occurred. (Edge hub is unable to connect to IoT Hub) ---> Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Edge hub is unable to connect to IoT Hub ---> System.AggregateException: One or more errors occurred. (Operation timeout expired.) (Unable to connect to the remote server) ---> System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c.<ApplyTimeout>b__79_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.<CreateAndOpenDeviceClient>d__23.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 168

**Comment by damonbarry** [comment]
No activity, closing. @carloshm please reopen if the problem still repros with GA bits.
