### ISSUE TITLE
EdgeAgent can't connect

### ISSUE THREAD

**Issue by Siddius** [Azure/iot-edge-v1#631]
## Info

- Version: V2 ( actual i am not sure how to find out )
- OS: Ubunutu 16.04 aarch64
- Used Image: microsoft/azureiotedge-agent:1.0.0-preview022-linux-arm32v7

## Issue Description

EdgeAgent can not connect. It seems for some reason it is resetting the connection instead of changing the cipher and establishing the TLS connection.

### Docker Logs

```
2018-06-26 10:35:21.092 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Starting module management agent.
2018-06-26 10:35:22.384 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Version - 1.0.0-preview022.11567621 (12a8e1bb63e619b17ca685efd470ad3f412034f4)
2018-06-26 10:35:22.386 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-06-26 10:35:23.049 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.DeviceClient] - Edge agent attempting to connect to IoT Hub via AMQP...
2018-06-26 10:35:24.139 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.ConfigSources.TwinConfigSource] - TwinConfigSource Created
2018-06-26 10:35:24.151 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.FileBackupConfigSource] - Edge agent config backup created here - backup.json
2018-06-26 10:35:36.625 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Starting module management agent.
2018-06-26 10:35:37.918 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Version - 1.0.0-preview022.11567621 (12a8e1bb63e619b17ca685efd470ad3f412034f4)
2018-06-26 10:35:37.919 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-06-26 10:35:38.578 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.DeviceClient] - Edge agent attempting to connect to IoT Hub via AMQP...
2018-06-26 10:35:39.892 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.ConfigSources.TwinConfigSource] - TwinConfigSource Created
2018-06-26 10:35:39.914 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.FileBackupConfigSource] - Edge agent config backup created here - backup.json
```

### Docker environment

```
docker exec edgeAgent printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=28ccf562897e
NetworkId=azure-iot-edge
RuntimeLogLevel=debug
EdgeModuleVolumePath=/mnt/edgemodule
EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
EdgeModuleHubServerCAChainCertificateFile=/mnt/edgehub/edge-chain-ca.cert.pem
EdgeModuleVolumeName=edgemodule
DockerLoggingDriver=json-file
UpstreamProtocol=
EdgeModuleHubServerCertificateFile=/mnt/edgehub/edge-hub-server.cert.pfx
DockerUri=unix:///var/run/docker.sock
EdgeHubVolumePath=/mnt/edgehub
DockerLoggingOptions__max-size=10m
EdgeDeviceHostName=rcar
DeviceConnectionString=**************************************************************
EdgeHubVolumeName=edgehub
DOTNET_VERSION=2.0.6
DOTNET_DOWNLOAD_URL=https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.6/dotnet-runtime-2.0.6-linux-arm.tar.gz
DOTNET_DOWNLOAD_SHA=367ac4cef9507f8776edca8c73886dd100c1ad19a994139a0076c02426abac5ad1750ee16306c10be3fa6c428edcb02045ddbcd5b4603734a7b2a55ed0c4213a
HOME=/root
```

### TCPDump

```
192 175.847305     192.168.178.27        40.127.132.17         TCP      74     50437 → 5671 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=844966 TSecr=0 WS=128

Frame 192: 74 bytes on wire (592 bits), 74 bytes captured (592 bits) on interface 0
Ethernet II, Src: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f), Dst: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd)
Internet Protocol Version 4, Src: 192.168.178.27, Dst: 40.127.132.17
Transmission Control Protocol, Src Port: 50437, Dst Port: 5671, Seq: 0, Len: 0

    193 175.907037     40.127.132.17         192.168.178.27        TCP      74     5671 → 50437 [SYN, ACK] Seq=0 Ack=1 Win=14480 Len=0 MSS=1460 SACK_PERM=1 TSval=4063612619 TSecr=844966 WS=512

Frame 193: 74 bytes on wire (592 bits), 74 bytes captured (592 bits) on interface 0
Ethernet II, Src: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd), Dst: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f)
Internet Protocol Version 4, Src: 40.127.132.17, Dst: 192.168.178.27
Transmission Control Protocol, Src Port: 5671, Dst Port: 50437, Seq: 0, Ack: 1, Len: 0

    194 175.907303     192.168.178.27        40.127.132.17         TCP      66     50437 → 5671 [ACK] Seq=1 Ack=1 Win=29312 Len=0 TSval=844981 TSecr=4063612619

Frame 194: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f), Dst: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd)
Internet Protocol Version 4, Src: 192.168.178.27, Dst: 40.127.132.17
Transmission Control Protocol, Src Port: 50437, Dst Port: 5671, Seq: 1, Ack: 1, Len: 0

    195 176.400906     192.168.178.27        40.127.132.17         TLSv1.2  363    Client Hello

Frame 195: 363 bytes on wire (2904 bits), 363 bytes captured (2904 bits) on interface 0
Ethernet II, Src: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f), Dst: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd)
Internet Protocol Version 4, Src: 192.168.178.27, Dst: 40.127.132.17
Transmission Control Protocol, Src Port: 50437, Dst Port: 5671, Seq: 1, Ack: 1, Len: 297
Secure Sockets Layer
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 292
        Handshake Protocol: Client Hello

    196 176.467839     40.127.132.17         192.168.178.27        TCP      66     5671 → 50437 [ACK] Seq=1 Ack=298 Win=15872 Len=0 TSval=4063613172 TSecr=845105

Frame 196: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd), Dst: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f)
Internet Protocol Version 4, Src: 40.127.132.17, Dst: 192.168.178.27
Transmission Control Protocol, Src Port: 5671, Dst Port: 50437, Seq: 1, Ack: 298, Len: 0

    197 176.489989     40.127.132.17         192.168.178.27        TCP      1514   [TCP segment of a reassembled PDU]

Frame 197: 1514 bytes on wire (12112 bits), 1514 bytes captured (12112 bits) on interface 0
Ethernet II, Src: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd), Dst: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f)
Internet Protocol Version 4, Src: 40.127.132.17, Dst: 192.168.178.27
Transmission Control Protocol, Src Port: 5671, Dst Port: 50437, Seq: 1, Ack: 298, Len: 1448

    198 176.490186     192.168.178.27        40.127.132.17         TCP      66     50437 → 5671 [ACK] Seq=298 Ack=1449 Win=27904 Len=0 TSval=845127 TSecr=4063613203

Frame 198: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f), Dst: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd)
Internet Protocol Version 4, Src: 192.168.178.27, Dst: 40.127.132.17
Transmission Control Protocol, Src Port: 50437, Dst Port: 5671, Seq: 298, Ack: 1449, Len: 0

    199 176.497944     40.127.132.17         192.168.178.27        TCP      1514   [TCP segment of a reassembled PDU]

Frame 199: 1514 bytes on wire (12112 bits), 1514 bytes captured (12112 bits) on interface 0
Ethernet II, Src: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd), Dst: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f)
Internet Protocol Version 4, Src: 40.127.132.17, Dst: 192.168.178.27
Transmission Control Protocol, Src Port: 5671, Dst Port: 50437, Seq: 1449, Ack: 298, Len: 1448

    200 176.498048     40.127.132.17         192.168.178.27        TLSv1.2  887    Server Hello, Certificate, Server Key Exchange, Certificate Request, Server Hello Done

Frame 200: 887 bytes on wire (7096 bits), 887 bytes captured (7096 bits) on interface 0
Ethernet II, Src: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd), Dst: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f)
Internet Protocol Version 4, Src: 40.127.132.17, Dst: 192.168.178.27
Transmission Control Protocol, Src Port: 5671, Dst Port: 50437, Seq: 2897, Ack: 298, Len: 821
[3 Reassembled TCP Segments (3717 bytes): #197(1448), #199(1448), #200(821)]
Secure Sockets Layer
    TLSv1.2 Record Layer: Handshake Protocol: Multiple Handshake Messages
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 3712
        Handshake Protocol: Server Hello
        Handshake Protocol: Certificate
        Handshake Protocol: Server Key Exchange
        Handshake Protocol: Certificate Request
        Handshake Protocol: Server Hello Done

    201 176.498177     192.168.178.27        40.127.132.17         TCP      66     50437 → 5671 [ACK] Seq=298 Ack=2897 Win=26496 Len=0 TSval=845129 TSecr=4063613203

Frame 201: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f), Dst: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd)
Internet Protocol Version 4, Src: 192.168.178.27, Dst: 40.127.132.17
Transmission Control Protocol, Src Port: 50437, Dst Port: 5671, Seq: 298, Ack: 2897, Len: 0

    202 176.498193     192.168.178.27        40.127.132.17         TCP      66     50437 → 5671 [ACK] Seq=298 Ack=3718 Win=25728 Len=0 TSval=845129 TSecr=4063613203

Frame 202: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f), Dst: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd)
Internet Protocol Version 4, Src: 192.168.178.27, Dst: 40.127.132.17
Transmission Control Protocol, Src Port: 50437, Dst Port: 5671, Seq: 298, Ack: 3718, Len: 0

    203 176.613033     192.168.178.27        40.127.132.17         TCP      66     50437 → 5671 [RST, ACK] Seq=298 Ack=3718 Win=25728 Len=0 TSval=845158 TSecr=4063613203

Frame 203: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: 2e:09:0a:01:9a:2f (2e:09:0a:01:9a:2f), Dst: 44:4e:6d:19:76:bd (44:4e:6d:19:76:bd)
Internet Protocol Version 4, Src: 192.168.178.27, Dst: 40.127.132.17
Transmission Control Protocol, Src Port: 50437, Dst Port: 5671, Seq: 298, Ack: 3718, Len: 0
```

**Comment by varunpuranik** [comment]
Hi Siddius, 
I am not sure why your EdgeAgent is getting into this state. We have released [version 1.0 of the Edge runtime](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux). Can you please give that a try to see if that solves your problem? 

If you want to continue with the current bits, I would suggest deleting all modules (docker rm -f $(docker ps -aq)), and restarting the edge runtime - iotedgectl restart, to see if that fixes the problem.

**Comment by Siddius** [comment]
Hi  @varunpuranik ,

thx for your reply. I tried restarting and even reinstalling the system, based on the Ubuntu16.04 rootfs image. 

Its nice to see a new version, but only for ubuntu and only armhf and not aarch64. But i will try to rip your packages apart and try to make it work. 

A version for aarch64 and espacially distribution independed would be very usefull. In my case Ubuntu is just the first step, target distro is yocto based. Is there anything planed in near future ?

**Comment by Siddius** [comment]
I managed to start the service and the agent is running, but the agentHub is making trouble:


```
2018-06-28 11:22:15.776 +00:00 [FTL] - Unable to start Kestrel.
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2018-06-28 11:22:15.916 +00:00 [INF] - Starting MQTT head
2018-06-28 11:22:16.071 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2018-06-28 11:22:16.266 +00:00 [INF] - Starting AMQP head
2018-06-28 11:22:16.292 +00:00 [INF] - Started MQTT head
2018-06-28 11:22:16.778 +00:00 [INF] - Started AMQP head
2018-06-28 11:22:16.848 +00:00 [INF] - Stopping
2018-06-28 11:22:31.981 +00:00 [INF] - Stopped

Unhandled Exception: System.AggregateException: One or more errors occurred. (Permission denied) ---> System.Net.Sockets.SocketException: Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Edge.Hub.Http.HttpProtocolHead.StartAsync() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/HttpProtocolHead.cs:line 25
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 119
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 31
```

**Comment by varunpuranik** [comment]
I haven't seen this error before. Looks like it is having trouble starting the Http endpoint. Do you have anything else listening on the 443 port?

**Comment by Siddius** [comment]
I have nothing running before i start `iotedge.service`

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      4023/sshd       
tcp        0      0 192.168.178.27:39724    40.127.132.17:443       ESTABLISHED 7906/iotedged   
tcp6       0      0 :::22                   :::*                    LISTEN      4023/sshd       
udp        0      0 172.17.0.1:123          0.0.0.0:*                           4211/ntpd       
udp        0      0 192.168.178.27:123      0.0.0.0:*                           4211/ntpd       
udp        0      0 127.0.0.1:123           0.0.0.0:*                           4211/ntpd       
udp        0      0 0.0.0.0:123             0.0.0.0:*                           4211/ntpd       
udp6       0      0 fe80::e839:61ff:fe3:123 :::*                                4211/ntpd       
udp6       0      0 fe80::42:59ff:fe5a::123 :::*                                4211/ntpd       
udp6       0      0 fe80::2c09:aff:fe01:123 :::*                                4211/ntpd       
udp6       0      0 ::1:123                 :::*                                4211/ntpd       
udp6       0      0 :::123                  :::*                                4211/ntpd       
Active UNIX domain sockets (servers and established)
```

Only when starting, `docker-proxy` is taking 443@ipv6, which should be okay.

```
tcp        0      0 192.168.178.27:39772    40.127.132.17:443       ESTABLISHED 11838/iotedged  
tcp6       0      0 :::5671                 :::*                    LISTEN      12115/docker-proxy
tcp6       0      0 :::8883                 :::*                    LISTEN      12103/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      4023/sshd       
tcp6       0      0 :::443                  :::*                    LISTEN      12135/docker-proxy
```

**Comment by damonbarry** [comment]
@Siddius are you still seeing the same issue when running with our stable (1.0) bits?

**Comment by Siddius** [comment]
@damonbarry last two comments are with 1.0, but the topic question was opened on the preview version. i guess this can be closed, also not solved. 
I opened a ticket in iotedge Project for the Problem in 1.0 see: https://github.com/Azure/iotedge/issues/9

**Comment by damonbarry** [comment]
Sounds good. I'll close this issue...

**Comment by Shrunoti** [comment]
Hi,

I am also trying to make iotedge work on aarch64. Following this thread, it seems that @Siddius has made 1.0  work with aarch64. Can I get a rundown on how to do that ?
