### ISSUE TITLE
edgeHub crash 

### ISSUE THREAD

**Issue by SachaLhopital** [Azure/iot-edge-v1#647]
Hello everyone, 

Since yesterday, I am unable to run my Iot Edge Device due to an edgeHub problem. The module crash quickly after `iotedgectl start` with the error below from the logs : 

```shell
sudo docker logs edgeHub
[2018-08-03 07:07:39 : Starting Edge Hub
[08/03/2018 07:07:39.874 AM] Edge Hub Main()

Unhandled Exception: System.AggregateException: One or more errors occurred. (error:2006D080:BIO routines:BIO_new_file:no such file) ---> Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetServerCertificatesFromFile(String certPath, String certName) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 213
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 65
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 31
``` 

- **V1 or V2 issue :** V1
- **OS version and architecture used :** Me and my team tried to install the iot edge runtime on an Ubuntu 18.04 gateway, on a windows 10 computer but the same error appear. 

For your information, we also create a new iot edge device and an iot edge hub from scratch (with no module in it except edgeAgent and edgeHub, but it crashes anyway. 

Anyway, we manage to solve the problem by changing the edgeHub container version. Indeed the error appears while trying to run the `mcr.microsoft.com/azureiotedge-hub:1.0` but it was resolved using the old *preview* image : `microsoft/azureiotedge-hub:1.0-preview`. This is certainly **not** a good solution, but we manage to resolve the problem that way. **Also noticed that only the edgeHub image was rollback to the previous one**, not the edgeAgent which is still in 1.0 version. 

Any idea how to solve the problem ? 
We found the same issue [here](https://github.com/Azure/iotedge/issues/22) but it was on an ARM architecture with is not our cases. We found other issues but no other solutions so far. 

Thanks for the help and good day ! 👍

**Comment by SachaLhopital** [comment]
After some digging, the Microsoft Support find the solution. 

**It seems that `iotedgectl` is now deprecated !** The new command to use is `iotedge`. 
 
More info in the doc below : 
[IoT Edge - Quickstart Linux](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux)
[IoT Edge - Quickstart](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart)
[IoT Edge - Tutorial CSharp Module](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module)
[IoT Edge - Troubleshoot](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot)
