### ISSUE TITLE
EdgeHub module was not able to start

### ISSUE THREAD

**Issue by VitorX** [Azure/iot-edge-v1#653]
# IoTEdge version
iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

# Description of the issue:
**edgeHub** module is not able to start.
NAME                     STATUS           DESCRIPTION                CONFIG
DemoDirectMethod2Module  failed           Failed (139) a minute ago  azurecontainerrigistryfei2.azurecr.io/demodirectmethod2module:0.0.1-amd64
tempSensor               running          Up 14 minutes              mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeHub                  stopped          Stopped                    mcr.microsoft.com/azureiotedge-hub:1.0
edgeAgent                running          Up 15 minutes              mcr.microsoft.com/azureiotedge-agent:1.0

# Console log of the issue:
 [Stop module edgeHub]
  [Start module edgeHub]
  [Saving edgeHub to store]
)"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module edgeHub: Container runtime error - ApiError(ApiError { code: InternalServerError, content: Some(Object({"message": String("driver failed programming external connectivity on endpoint edgeHub (fa6e7df891491feee3cf66aa4ddf82e8547fee17d5c6e95447db15f2d19409b5): **Error starting userland proxy: Bind for 0.0.0.0:443: unexpected error Permission denied"**)})) }), StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 142
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 36
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61

**Comment by aribeironovaes** [comment]
Hi @VitorX , 

Since this issue is on edge V2, can you open an issue there? We are trying to more issues from V1 to V2, so we can concentrate specific issues there. 

Also, from your logs I see that you are using iotedge version 1.0.0, we just had a release, can you also update your iotedge version so we can make sure you have the latest bits? 

Also, add more information about your envionment. Linux? Windows?

Thanks, 

Angelo Ribeiro.

**Comment by aribeironovaes** [comment]
Closing so we can follow up on issues on v2 github.
